name: Release

on: [workflow_dispatch]

jobs:
  release:
    name: create release
    runs-on: ubuntu-22.04
    env:
      REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
      RELEASE_VERSION: ${{ github.run_number }}
      OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Create release branch
        run: git checkout -b releases/$RELEASE_VERSION
      - name: Push to release branch
        run: git push origin releases/$RELEASE_VERSION
      - name: Build
        run: docker build . -t cr.yandex/${{ secrets.REGISTRY_ID }}/app:${{ github.run_number }} -t cr.yandex/${{ secrets.REGISTRY_ID }}/app:${{ github.run_number }}_latest
      - name: Login to Cloud
        run: echo $OAUTH_TOKEN | docker login --username oauth --password-stdin cr.yandex
      - name:  Load Docker-image to Container Registry
        run: |
            docker push cr.yandex/${REGISTRY_ID}/app:${RELEASE_VERSION}
            docker push cr.yandex/${REGISTRY_ID}/app:${RELEASE_VERSION}_latest
            
